#==========================
# SCpkg Configuration
#==========================

Repository=file:///packages

EnableDebian=yes

AutoFallback=yes

Architecture=x86_64

CacheDir=/var/cache/scpkg

DatabaseDir=/var/lib/scpkg
